### ISSUE TITLE
Feature Request: Add OpenAI Endpoint Configuration Option

### ISSUE THREAD

**Issue by josangmi** [neozhang/you-and-your-research#1]
Feature Request: Add OpenAI Endpoint Configuration Option
Summary
Add a configuration option in the "You and Your Research" plugin settings to allow users to set a custom OpenAI API endpoint.

Description
Currently, the plugin allows users to input their OpenAI API key but lacks a configuration option for setting a custom OpenAI endpoint. This addition would provide more flexibility for users who need to interact with different OpenAI endpoints, such as those provided for private instances or regional services.

Proposed Solution
UI Update:

Add a new input field labeled "OpenAI Endpoint" below the "OpenAI API Key" field in the settings menu (see attached screenshot for reference).
Placeholder text for the input field could be https://api.openai.com/v1.
Backend Changes:

Modify the plugin's code to use the custom endpoint provided by the user instead of the default one.
Ensure that if the endpoint is not set by the user, the plugin defaults to https://api.openai.com/v1.
Validation:

Add basic validation to ensure the endpoint URL is properly formatted.

**Comment by neozhang** [comment]
This issue has been resolved in the [0.9.7 release](https://github.com/neozhang/you-and-your-research/releases/tag/0.9.7). Thanks for the advice!
